![[Pasted image 20240708153336.png]]
A promise in JavaScript is an object representing the eventual completion(or failure) of an asynchronous operation and its resulting values. 
##### Usage of Promises,
Promises are used to handle asynchronous operations. 
Ex: 
	Network requests
	File reading
	Timer
Promises allow us to chain operations and manage errors more easily.
##### Key states of a promise,

| promise.state | promise.result  | Description                                        |
| ------------- | --------------- | -------------------------------------------------- |
| pending       | undefined       | The initial state, neither fulfilled nor rejected. |
| fullfilled    | a result value  | The operation completed successfully.              |
| rejected      | an error object | The operation failed.                              |
##### Creating a Promise
The **Promise constructor** is used to create a promise, which takes a functions(executor) with two parameters. 
1. resolve
	Called when asynchronous operation completes successfully.
	Takes a single argument, which is the value that the promise will be fulfilled with.
	Once called, the promise transitions from the pending state to the fulfilled state.
2. reject
	Called when the asynchronous operation encounters an error.
	Takes a single argument, which is the reason for the rejection (usually an error object).
	Once called, the promise transitions from the pending state to the rejected state.
```js
const myPromise = new Promise((resolve, reject) => {
	setTimeout(() => {
		if(Math.random() > 0.5)
		{
			resolve("Operation was successful!");
		} else {
			reject(new Error("Operation failed!");
		}
	}, 1000)
});
```
-  The executor function can only call `resolve` or `reject` once. Subsequent call will be ignored.
- The resolve or reject functions should only call from inside the executor function. 
	(Because they are internal mechanism to handle the promise.)

##### Consuming a Promise
We can use below methods to handle the result of the promise. 
1. **.then()** : used to handle a resolved promise
2. **catch()** : used to handle a rejected promise
3. **finally()** : used for code than should run regardless of the promise being fulfilled or rejected. 
Ex:
```js
myPromise
	.then((result) => {
		console.log(result);
	})
	.catch((error) => {
		console.error(error);
	})
	.finally(() => {
		console.log('Operation completed.');
	})
```

##### Chaining a promise
Promises can be chained to perform a sequence of asynchronous operations. 
```js
const firstPromise = new Promise((resolve, reject) => {
	setTimeout(() => resolve('first operation complete'), 1000);
})

firstPromise
	.then((result) => {
		console.log(result); //first operation complete
		return new Promise((resolve, reject) => {
			settimeout(() => resolve('Second operation complete'), 1000);
		})
	})
	.then((result) => {
		console.log(reuslt); //'Second operation complete'
	})
	.catch((error) => {
		console.log(error); 
	})
```

##### Promise concurrency
The `Promise` class offer f static methods to facilitate async task,
1. **Promise.all(iterable)**
	Takes an iterable of promises.(ex: array)
	Fulfills when **all** of the promises fulfill.
	Rejects when **any** of the promises rejects.
2. **Promise.allSettled(iterable)**
	Takes an iterable of promises.(ex: array)
	Fulfills when all promises settle. 
3. **Promise.any(iterable)**
	Takes an iterable of promises.(ex: array)
	Fulfills when **any** of the promises fulfills.
	Rejects when **all** of the promises reject.
4. **Promise.race(iterable)**
	Takes an iterable of promises.(ex: array)
	Fulfills when any of the promises fulfills.
	Rejects when any of the promises rejects.
##### 'promise.all()'
`promise.all` allows you to wait for multiple promises to resolve. It takes an array of promises and returns a new promise that resolve when all of the input promises have resolved. 
Ex:
```js
const promise1 = new Promise((resolve) => setTimeout(() => resolve('First'),1000));
const promise2 = new Promise((resolve) => setTimeout(() => resolve('Second'),2000));

Prmise.all([promise1, promise2])
	.then((result) => {
		console.log(result); //['first', 'Second']
	})
	.catch((error) => {
		console.error(error);
	})
```

##### Using `async` and `await`
`async` and `await` keywords provide a more readable and concise way to work with promises. 
```js
async function asyncFunction()
{
	try{
		const reuslt1 = await firstPromise;
		console.log(result1); //'First operation complete'
		
		const result2 = await secondPromise((resolve, reject) => {
			setTimeout(() => resolve('Second operation complete'), 1000);
		});
		consle.log(result2); //'Second operation complete'
	}
	catch(error) {
		console.log(error);
	}
}
syncFunction();
```

*****
##### Under the hood, `async` functions and `await` expressions work with Promises. 
When you use `await` in an `async` function, you are telling JavaScript to wait until the Promise following `await` settles (either resolved or rejected) before moving on to the next line of code.

**`async` keyword,**
- Declaring a function as `sync` means it returns a promise. 
-  The function will automatically returns a resolved promise with the value if the functions returns a value.
- If the functions throws and error, it will automatically return a rejected promise with the thrown error. 

**`await` keyword,**
- The `await` keyword can only used inside a `aync` function.
- It pauses the execution of the `sync` function until the promise is resolved or rejected.
- It allows you to write async code in synchronous style, making it easier to follow and understand.

EX: When you mark a function as `async`, it returns a Promise
```js
async fucntion exampleFunction(){
	return 'Hello, world!';
}

exampleFunction()
	.then((result) => {
		console.log(result); //logs 'Hello, world!'
	})
```

Ex: Use `await` to wait for a Promise to resolve inside an `async` function.
```js
async function fetchData()
{
	const response = await fetch('https://api.example.com/data');
	const data = await response.json();
	console.log(data);
}
fetchData();
```
- The `await fetch('https://api.example.com/data')` line pauses the execution of `fetchData` until the `fetch` Promise resolves.
- Once the Promise is resolved, the function resumes execution, assigning the resolved value to `response`.
- The next `await response.json()` line again pauses until `response.json()` resolves, and then assigns the resolved value to `data`.

###### Converting promise chain into `async`/`await`
Promise chain
```js
function fetchData()
{
	return fect('https://api.example.com/data')
		.then(response => response.json())
		.then(data => {
			console.log(data);
			return data;
		})
		.catch(error => {
			console.log('Error: ', error);
		});
}
fecthData();
```
Using `sync/await`
```js
async function fetchData()
{
	try{
		const response = await fetch('https://api.example.com/data');
		const data = await response.json();
		console.log(data);
		retrn data;
	} catch(error){
		console.error('Error: ', error)
	}
}
fetchData();
```
Differences,
	The function is declared `async`, so it returns a promise.
	`await` is used to pause the function execution until the promises are resolved.
	`try/catch` block us used to handle any errors that occur during the asynchronous operation. 